name: browsers-full
on:
  # Once a week on Thursday at 02:15
  schedule:
    - cron: '15 2 * * 4'
  # Or manually
  workflow_dispatch:
  # Or when developing this workflow
  push:
    paths:
      - .github/workflows/browsers-full.yaml

jobs:
  run:
    name: BrowserStack
    runs-on: ubuntu-latest
    env:
      PUPPETEER_DOWNLOAD_PATH: ~/.puppeteer_download
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.puppeteer_download
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js 10
        uses: actions/setup-node@v2
        with:
          node-version: 10.x

      - name: Prepare
        run: |
          npm ci
          npm run build

      - name: Tests
        run: npm run browserstack
        env:
          BROWSERSTACK_JSON: build/browserstack-full.json
          BROWSERSTACK_USERNAME: "${{ secrets.BROWSERSTACK_USERNAME }}"
          BROWSERSTACK_KEY: "${{ secrets.BROWSERSTACK_KEY }}"
          # Set "project" metadata
          TRAVIS_REPO_SLUG: "${{ github.repository }} ${{ github.event_name }}"
          # Set "commit" metadata
          TRAVIS_COMMIT: "full ${{ github.ref }} ${{ github.sha }}"
          TUNNEL_ID: "${{ github.event_name }}-full-${{ github.sha }}"
