name: Code coverage
on:
  - push

jobs:
  run:
    name: Code coverage
    if: ${{ github.repository == 'qunitjs/qunit' }} # skip on forks, needs secret
    runs-on: ubuntu-20.04
    env:
      PUPPETEER_DOWNLOAD_PATH: "${{ github.workspace }}/.puppeteer_download"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.puppeteer_download
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: npm ci

      - name: Tests
        run: npm run coverage

      - run: npm run coveralls-upload
        env:
          COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
          COVERALLS_GIT_BRANCH: "${{ github.ref }}"
          COVERALLS_SERVICE_NAME: github-actions
          COVERALLS_SERVICE_JOB_ID: "${{ github.run_id }}"
